packages:
  - "apps/*"
  - "packages/*"

# Approved build scripts - these packages legitimately need to run build scripts
# esbuild, workerd, sharp need native binaries for performance
# @heroui/shared-utils needs build steps for UI components
# unrs-resolver is a dependency that needs compilation
allowBuilds:
  "@heroui/shared-utils": true
  "esbuild": true
  "sharp": true
  "unrs-resolver": true
  "workerd": true
